### ISSUE TITLE
bootstrap package 

### ISSUE THREAD

**Issue by andrewlorenz** [METEOR-HACK-2015-OCT-BIRMINGHAM-UK/Idea2#1]
I use this bootstrap package which is very neat:
twbs:bootstrap                   3.3.5  The most popular front-end framework ...

but this deployment is using a different one which appears to be quite messy (not properly integrated into the meteor framework) ?:
nemo64:bootstrap           3.3.5_2  Highly configurable bootstrap integration.

**Comment by seanbutler** [comment]
agreed. we use twbs:bootstrap on our project at truckulus.
the boilerplate looks well engineered and structured but i think its causing me headaches getting new features added in.
